export const part = [
  // ─────────────────────────── КВАДРИЦЕПС ───────────────────────────
  {
    s: 'back-squat', ru: 'Приседания со штангой на спине', en: 'Back Squat',
    f: 'squat', c: 'powerlifting', p: 'squat', comp: true, pp: 'push',
    eq: 'barbell', pm: 'quads,glutes', sm: 'hamstrings,lower_back,abs',
    al: 'присед|приседания|back squat|присед со штангой', tg: 'база,ноги',
    rest: 240, pop: 98, d: 'intermediate',
    ov: 'Базовое движение для ног. Штанга на верхе трапеций или чуть ниже, корпус жёсткий, таз и колени сгибаются одновременно.',
    st: [
      'Снимите штангу со стоек, сделайте 2–3 шага назад, стопы на ширине плеч, носки слегка наружу.',
      'Сделайте вдох, напрягите пресс, «вкрутите» стопы в пол.',
      'Начните движение, одновременно сгибая таз и колени, спина сохраняет нейтральное положение.',
      'Опуститесь минимум до параллели бедра с полом.',
      'Мощно поднимитесь, отталкиваясь всей стопой; таз и грудь идут вверх одновременно.',
    ],
    mi: [
      'Колени заваливаются внутрь.',
      'Таз уходит вверх раньше груди — «доброе утро» вместо приседа.',
      'Отрыв пяток.',
      'Округление поясницы в нижней точке.',
    ],
    ti: ['Работайте в силовой раме с ограничителями.', 'Глубину определяйте подвижностью, а не чужими видео.'],
  },
  {
    s: 'front-squat', ru: 'Фронтальные приседания', en: 'Front Squat',
    f: 'squat', c: 'weightlifting', p: 'squat', comp: true, pp: 'push',
    eq: 'barbell', pm: 'quads', sm: 'glutes,abs,shoulders',
    al: 'фронтальный присед|front squat|присед на груди', tg: 'ноги,квадрицепс',
    rest: 210, pop: 62, d: 'advanced',
  },
  {
    s: 'smith-squat', ru: 'Приседания в Смите', en: 'Smith Machine Squat',
    f: 'squat', c: 'bodybuilding', p: 'squat', comp: true, pp: 'push',
    eq: 'smith', pm: 'quads,glutes', sm: 'hamstrings',
    al: 'присед в смите|smith squat', tg: 'ноги,тренажёр', rest: 180, pop: 56,
  },
  {
    s: 'hack-squat', ru: 'Гакк-приседания', en: 'Hack Squat',
    f: 'squat', c: 'bodybuilding', p: 'squat', comp: true, pp: 'push',
    eq: 'machine', pm: 'quads', sm: 'glutes',
    al: 'гакк|hack squat|гак присед', tg: 'ноги,тренажёр', rest: 180, pop: 68,
  },
  {
    s: 'leg-press', ru: 'Жим ногами', en: 'Leg Press',
    f: 'squat', c: 'bodybuilding', p: 'squat', comp: true, pp: 'push',
    eq: 'machine', pm: 'quads,glutes', sm: 'hamstrings',
    al: 'жим ногами|leg press|платформа', tg: 'ноги,тренажёр', rest: 180, pop: 90,
    ov: 'Жим платформы ногами. Позволяет нагрузить ноги без осевой нагрузки на позвоночник. Поясница должна оставаться прижатой к спинке.',
    mi: ['Отрыв таза от спинки в нижней точке — прямой риск для поясницы.', 'Полное выпрямление коленей с «щелчком».', 'Слишком узкая постановка стоп при большом весе.'],
  },
  {
    s: 'bulgarian-split-squat', ru: 'Болгарские выпады', en: 'Bulgarian Split Squat',
    f: 'lunge', c: 'bodybuilding', p: 'lunge', comp: true, pp: 'push', lat: 'unilateral',
    eq: 'dumbbell,bench', pm: 'quads,glutes', sm: 'hamstrings,abs',
    al: 'болгарские|сплит присед|bulgarian', tg: 'ноги,одна нога', rest: 150, pop: 74,
  },
  {
    s: 'walking-lunge', ru: 'Выпады с ходьбой', en: 'Walking Lunge',
    f: 'lunge', c: 'functional', p: 'lunge', comp: true, pp: 'push', lat: 'alternating',
    eq: 'dumbbell', pm: 'quads,glutes', sm: 'hamstrings,abs',
    al: 'выпады|выпады с ходьбой|lunges', tg: 'ноги', rest: 120, pop: 72,
  },
  {
    s: 'reverse-lunge', ru: 'Обратные выпады', en: 'Reverse Lunge',
    f: 'lunge', c: 'bodybuilding', p: 'lunge', comp: true, pp: 'push', lat: 'alternating',
    eq: 'dumbbell', pm: 'quads,glutes', sm: 'hamstrings',
    al: 'выпады назад|reverse lunge', tg: 'ноги', rest: 120, pop: 58,
  },
  {
    s: 'step-up', ru: 'Зашагивания на тумбу', en: 'Step-Up',
    f: 'lunge', c: 'functional', p: 'lunge', comp: true, pp: 'push', lat: 'unilateral',
    eq: 'dumbbell,box', pm: 'quads,glutes', sm: 'hamstrings',
    al: 'зашагивания|step up', tg: 'ноги,функциональный', rest: 120, pop: 54,
  },
  {
    s: 'goblet-squat', ru: 'Гоблет-приседания', en: 'Goblet Squat',
    f: 'squat', c: 'functional', p: 'squat', comp: true, pp: 'push',
    eq: 'dumbbell,kettlebell', pm: 'quads,glutes', sm: 'abs',
    al: 'гоблет|goblet|присед с гантелью', tg: 'ноги,новичок', rest: 120, pop: 66, d: 'beginner',
  },
  {
    s: 'leg-extension', ru: 'Разгибания ног в тренажёре', en: 'Leg Extension',
    f: 'leg_extension', c: 'bodybuilding', p: 'isolation', pp: 'push',
    eq: 'machine', pm: 'quads', sm: '',
    al: 'разгибания ног|leg extension|квадрицепс тренажер', tg: 'ноги,изоляция', rest: 90, pop: 82,
  },
  {
    s: 'sissy-squat', ru: 'Сисси-приседания', en: 'Sissy Squat',
    f: 'squat', c: 'bodybuilding', p: 'squat', m: 'bodyweight_reps', pp: 'push',
    eq: 'bodyweight', pm: 'quads', sm: '',
    al: 'сисси присед|sissy', tg: 'ноги,квадрицепс', rest: 90, pop: 26, d: 'advanced',
  },
  {
    s: 'bodyweight-squat', ru: 'Приседания без веса', en: 'Bodyweight Squat',
    f: 'squat', c: 'calisthenics', p: 'squat', m: 'bodyweight_reps', comp: true, pp: 'push',
    eq: 'bodyweight', pm: 'quads,glutes', sm: 'hamstrings',
    al: 'приседания без веса|воздушные приседания|air squat', tg: 'ноги,дома', rest: 60, pop: 60, d: 'beginner',
  },
  {
    s: 'pistol-squat', ru: 'Пистолетик', en: 'Pistol Squat',
    f: 'squat', c: 'calisthenics', p: 'squat', m: 'bodyweight_reps', comp: true, pp: 'push', lat: 'unilateral',
    eq: 'bodyweight', pm: 'quads,glutes', sm: 'hamstrings,abs',
    al: 'пистолетик|pistol squat|присед на одной', tg: 'ноги,свой вес', rest: 120, pop: 30, d: 'advanced',
  },
  {
    s: 'belt-squat', ru: 'Приседания с поясом', en: 'Belt Squat',
    f: 'squat', c: 'bodybuilding', p: 'squat', comp: true, pp: 'push',
    eq: 'machine', pm: 'quads,glutes', sm: 'hamstrings',
    al: 'belt squat|присед с поясом', tg: 'ноги,без осевой', rest: 150, pop: 24,
  },
  {
    s: 'zercher-squat', ru: 'Приседания Зерхера', en: 'Zercher Squat',
    f: 'squat', c: 'functional', p: 'squat', comp: true, pp: 'push',
    eq: 'barbell', pm: 'quads,glutes', sm: 'abs,lower_back',
    al: 'зерхер|zercher', tg: 'ноги', rest: 180, pop: 18, d: 'advanced',
  },

  // ─────────────────────────── БИЦЕПС БЕДРА ───────────────────────────
  {
    s: 'lying-leg-curl', ru: 'Сгибания ног лёжа', en: 'Lying Leg Curl',
    f: 'leg_curl', c: 'bodybuilding', p: 'isolation', pp: 'pull',
    eq: 'machine', pm: 'hamstrings', sm: 'calves',
    al: 'сгибания ног лежа|leg curl|бицепс бедра тренажер', tg: 'ноги,изоляция', rest: 90, pop: 84,
  },
  {
    s: 'seated-leg-curl', ru: 'Сгибания ног сидя', en: 'Seated Leg Curl',
    f: 'leg_curl', c: 'bodybuilding', p: 'isolation', pp: 'pull',
    eq: 'machine', pm: 'hamstrings', sm: 'calves',
    al: 'сгибания ног сидя', tg: 'ноги,изоляция', rest: 90, pop: 74,
  },
  {
    s: 'nordic-curl', ru: 'Нордические сгибания', en: 'Nordic Hamstring Curl',
    f: 'leg_curl', c: 'functional', p: 'isolation', m: 'bodyweight_reps', pp: 'pull',
    eq: 'bodyweight', pm: 'hamstrings', sm: 'glutes',
    al: 'нордик|nordic curl', tg: 'ноги,профилактика', rest: 150, pop: 30, d: 'advanced',
  },
  {
    s: 'stiff-leg-deadlift', ru: 'Мёртвая тяга на прямых ногах', en: 'Stiff-Leg Deadlift',
    f: 'deadlift', c: 'bodybuilding', p: 'hinge', comp: true, pp: 'pull',
    eq: 'barbell', pm: 'hamstrings', sm: 'glutes,lower_back',
    al: 'мертвая тяга|на прямых ногах|stiff leg', tg: 'ноги,задняя цепь', rest: 180, pop: 64,
  },
  {
    s: 'single-leg-rdl', ru: 'Румынская тяга на одной ноге', en: 'Single-Leg RDL',
    f: 'deadlift', c: 'functional', p: 'hinge', comp: true, pp: 'pull', lat: 'unilateral',
    eq: 'dumbbell', pm: 'hamstrings,glutes', sm: 'lower_back,abs',
    al: 'румынка на одной|single leg rdl', tg: 'ноги,баланс', rest: 120, pop: 40,
  },
  {
    s: 'glute-ham-raise', ru: 'Подъём корпуса в GHD', en: 'Glute-Ham Raise',
    f: 'leg_curl', c: 'functional', p: 'hinge', m: 'bodyweight_reps', pp: 'pull',
    eq: 'machine', pm: 'hamstrings,glutes', sm: 'lower_back',
    al: 'ghd|glute ham', tg: 'ноги,задняя цепь', rest: 120, pop: 22, d: 'advanced',
  },

  // ─────────────────────────── ЯГОДИЦЫ ───────────────────────────
  {
    s: 'hip-thrust', ru: 'Ягодичный мост со штангой', en: 'Barbell Hip Thrust',
    f: 'hip_thrust', c: 'bodybuilding', p: 'hinge', comp: true, pp: 'push',
    eq: 'barbell,bench', pm: 'glutes', sm: 'hamstrings,quads',
    al: 'ягодичный мост|hip thrust|тазовый мост', tg: 'ягодицы', rest: 150, pop: 78,
    ov: 'Основное движение для ягодичных. Лопатки на скамье, подбородок прижат, движение заканчивается полным разгибанием таза без прогиба в пояснице.',
    mi: ['Переразгибание поясницы вместо разгибания таза.', 'Слишком высокая скамья.', 'Взгляд вверх — уводит корпус в прогиб.'],
  },
  {
    s: 'glute-bridge', ru: 'Ягодичный мостик с пола', en: 'Glute Bridge',
    f: 'hip_thrust', c: 'bodybuilding', p: 'hinge', m: 'weighted_bodyweight', pp: 'push',
    eq: 'bodyweight', pm: 'glutes', sm: 'hamstrings',
    al: 'мостик|glute bridge', tg: 'ягодицы,дома', rest: 90, pop: 54, d: 'beginner',
  },
  {
    s: 'cable-kickback', ru: 'Отведение ноги назад в блоке', en: 'Cable Glute Kickback',
    f: 'glute_iso', c: 'bodybuilding', p: 'isolation', pp: 'push', lat: 'unilateral',
    eq: 'cable', pm: 'glutes', sm: 'hamstrings',
    al: 'махи ногой назад|kickback ягодицы', tg: 'ягодицы,изоляция', rest: 75, pop: 48,
  },
  {
    s: 'hip-abduction', ru: 'Отведение бедра в тренажёре', en: 'Hip Abduction Machine',
    f: 'glute_iso', c: 'bodybuilding', p: 'isolation', pp: 'push',
    eq: 'machine', pm: 'abductors,glutes', sm: '',
    al: 'разведение ног|отведение бедра|abduction', tg: 'ягодицы,тренажёр', rest: 75, pop: 62,
  },
  {
    s: 'hip-adduction', ru: 'Сведение ног в тренажёре', en: 'Hip Adduction Machine',
    f: 'glute_iso', c: 'bodybuilding', p: 'isolation', pp: 'pull',
    eq: 'machine', pm: 'adductors', sm: '',
    al: 'сведение ног|приводящие|adduction', tg: 'ноги,тренажёр', rest: 75, pop: 52,
  },
  {
    s: 'frog-pump', ru: 'Ягодичный мостик «лягушка»', en: 'Frog Pump',
    f: 'hip_thrust', c: 'bodybuilding', p: 'hinge', m: 'bodyweight_reps', pp: 'push',
    eq: 'bodyweight', pm: 'glutes', sm: '',
    al: 'лягушка|frog pump', tg: 'ягодицы,дома', rest: 60, pop: 24, d: 'beginner',
  },
  {
    s: 'band-lateral-walk', ru: 'Ходьба в резинке', en: 'Banded Lateral Walk',
    f: 'glute_iso', c: 'mobility', p: 'gait', m: 'reps_only', pp: 'push',
    eq: 'band', pm: 'abductors,glutes', sm: '',
    al: 'ходьба в резинке|monster walk', tg: 'ягодицы,разминка', rest: 60, pop: 34, d: 'beginner',
  },

  // ─────────────────────────── ИКРЫ ───────────────────────────
  {
    s: 'standing-calf-raise', ru: 'Подъёмы на носки стоя', en: 'Standing Calf Raise',
    f: 'calf_raise', c: 'bodybuilding', p: 'isolation', pp: 'push',
    eq: 'machine', pm: 'calves', sm: '',
    al: 'икры стоя|подъемы на носки|calf raise', tg: 'икры', rest: 75, pop: 74,
  },
  {
    s: 'seated-calf-raise', ru: 'Подъёмы на носки сидя', en: 'Seated Calf Raise',
    f: 'calf_raise', c: 'bodybuilding', p: 'isolation', pp: 'push',
    eq: 'machine', pm: 'calves', sm: '',
    al: 'икры сидя|камбаловидная', tg: 'икры', rest: 75, pop: 60,
  },
  {
    s: 'smith-calf-raise', ru: 'Подъёмы на носки в Смите', en: 'Smith Calf Raise',
    f: 'calf_raise', c: 'bodybuilding', p: 'isolation', pp: 'push',
    eq: 'smith', pm: 'calves', sm: '',
    al: 'икры в смите', tg: 'икры', rest: 75, pop: 36,
  },
  {
    s: 'leg-press-calf-raise', ru: 'Подъёмы на носки в жиме ногами', en: 'Leg Press Calf Raise',
    f: 'calf_raise', c: 'bodybuilding', p: 'isolation', pp: 'push',
    eq: 'machine', pm: 'calves', sm: '',
    al: 'икры в жиме ногами', tg: 'икры', rest: 75, pop: 40,
  },
  {
    s: 'single-leg-calf-raise', ru: 'Подъёмы на носок на одной ноге', en: 'Single-Leg Calf Raise',
    f: 'calf_raise', c: 'calisthenics', p: 'isolation', m: 'weighted_bodyweight', pp: 'push', lat: 'unilateral',
    eq: 'bodyweight,dumbbell', pm: 'calves', sm: '',
    al: 'икры на одной ноге', tg: 'икры,дома', rest: 60, pop: 32, d: 'beginner',
  },
];
